version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      timezone: "Asia/Tokyo"
      interval: "daily"
      time: "00:00"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      timezone: "Asia/Tokyo"
      interval: "daily"
      time: "00:00"

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      timezone: "Asia/Tokyo"
      interval: "daily"
      time: "00:00"
