name: Rust
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@bc2d2e71bd35c5549942babaa51a89c586b981d1 # v2.8.1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --all-targets --all-features --locked --verbose
